name: Release Database Connector Service
on:
  push:
    tags:
      - 'v*' # P

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Creating 'Release' Directory
        run: mkdir -p release/functions
      - name: Installing Packages for 'Image Processor' & Creating the Zip
        run: cd functions/image_processor/ && npm install --omit=dev && zip -r ../../release/functions/image_processor.zip .
      - name: Copying Project Template JSON
        run: cp project-template-1.0.0.json release/project-template-1.0.0.json
      - name: Creating Zip of Release Folder
        run: cd release && zip -r release.zip .

      # - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './release/release.zip'
          bodyFile: 'README.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}
